### ISSUE TITLE
关于生成歌词的长度

### ISSUE THREAD

**Issue by lvZic** [ForJadeForest/GPT2-Chinese-Lyrics-Rhymeaware#2]
针对生成的每句歌词 我想要固定长度 这个有什么办法做到呢

**Comment by ForJadeForest** [comment]
1.  采用回滚的方式生成，topk，temperature等参数保证生成的多样性的同时，只保留长度符合要求的输出。 
2. 修改数据集，筛选出符合你要求的数据，保证数据集中的长度都是固定的，采用这个数据集进行训练。（效果应该不错）
3. 修改模型结构，比如尝试加入一个长度embedding去引入额外的信息（具体没有实验过）

**Comment by lvZic** [comment]
> 1. 采用回滚的方式生成，topk，temperature等参数保证生成的多样性的同时，只保留长度符合要求的输出。
> 2. 修改数据集，筛选出符合你要求的数据，保证数据集中的长度都是固定的，采用这个数据集进行训练。（效果应该不错）
> 3. 修改模型结构，比如尝试加入一个长度embedding去引入额外的信息（具体没有实验过）

我是想有一首歌 将其中原本的歌词替换为新歌词。所以每一句新歌词长度需要固定的
1）方法效果不太稳定
2）方法针对每句歌词有不同长度就不好办了
3）我目前找到的是 https://github.com/lipiji/SongNet  但它要求有匹配长度的训练数据

**Comment by ForJadeForest** [comment]
简单看了下，songnet应该不需要对数据格式有特殊要求吧？

**Comment by lvZic** [comment]
> 简单看了下，songnet应该不需要对数据格式有特殊要求吧？

难道我理解错了 我意思是他需要相同模板的词来训练 也就是宋词的那些个固定词牌 
而现代歌曲每首歌每一句没有固定的格式

**Comment by ForJadeForest** [comment]
我的理解是对每一首歌词生成他的模板去作为embedding的输入，因此不需要每一首歌的格式都相同

**Comment by lvZic** [comment]
> 我的理解是对每一首歌词生成他的模板去作为embedding的输入，因此不需要每一首歌的格式都相同

好的 songnet需要找下中文歌曲歌词数据重新训练下 
但有一个问题是 songnet无法制定上文信息（生成的标题信息 prompt）这个有什么建议吗

**Comment by ForJadeForest** [comment]
你可以在训练的时候提供把标题拼接起来，然后对title添加不同的token_type_embedding～

**Comment by lvZic** [comment]
> 你可以在训练的时候提供把标题拼接起来，然后对title添加不同的token_type_embedding～

你的意思是 在songnet网络的基础上 加一层标题信息的embedding 代表prompt特征是吧

**Comment by ForJadeForest** [comment]
这样当然也可以，我的意思是把标题和歌词内容拼接起来，比如 《手写的从前》，xxxxxxx 这一整个部分作为文本进行输入，然后对于token_type_ids 可以设置为：[0,0,0,0,0,0,0,0, 1, 1, 1, 1, 1....., 1]（8个0，表示【《手写的从前》，】中的每一个字符），这样可以做一定程度的区分。
