### ISSUE TITLE
重新训练 50个epoch loss到2就很难继续下降了

### ISSUE THREAD

**Issue by lvZic** [ForJadeForest/GPT2-Chinese-Lyrics-Rhymeaware#3]
会是为什么呢

**Comment by ForJadeForest** [comment]
loss 值大小不能说明性能的高低，建议推理一下亲自查看模型效果 ~

**Comment by lvZic** [comment]
> loss 值大小不能说明性能的高低，建议推理一下亲自查看模型效果 ~

soga
能参考下你的loss 下降吗

**Comment by ForJadeForest** [comment]
不好意思，这是很久以前的项目了，Loss这种并没有保存。这边建议你在Loss收敛之后进行测试来查看模型的效果哦。
